# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Defa$
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is e$
  # scrape_timeout is set to the global default (10s).


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scrape$
  #- job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    #static_configs:
    #- targets: ['127.0.0.1:9090']

  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['xxx.xxx.xx.xx:9308']
